version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading-bot
    volumes:
      - ./:/app
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - trading-network
    restart: unless-stopped
    command: python trading_bot.py

  redis:
    image: redis:6.2-alpine
    container_name: trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  monitoring:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading-monitor
    volumes:
      - ./:/app
    depends_on:
      - trading-bot
      - redis
    networks:
      - trading-network
    ports:
      - "8000:8000"
    command: uvicorn monitoring.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

networks:
  trading-network:
    driver: bridge

volumes:
  redis-data:
